DELETE http://localhost:3000/users/10
Content-Type: application/json

{
  "name": "Prince",
  "email": "cyubahirodaniel@gmail.com"
}
###
PUT http://localhost:3000/users/10
Content-Type: application/json

{
  "name": "Prince",
  "email": "cyubahirodaniel@gmail.com"
}
###

GET http://localhost:3000/users/10
Accept: application/json

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Prince Daniel",
  "email": "cyubahirodaniel@gmail.com"
}

###
GET http://localhost:3000/users
Accept: application/json

###
